### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by engineerjai** [onodip/OpenMDAO-XDSM#5]
This package calls the following:

from openmdao.visualization.html_utils import (
    write_div,
    head_and_body,
    write_script,
    write_style,
)

but only returns errors as openmdao.visualization.html_utils doesn't seem to exist. Cannot get the tests to work with this either.

**Comment by onodip** [comment]
@engineerjai I will look into it. Could you tell me which OpenMDAO version are you using?

**Comment by onodip** [comment]
The html_utils.py file was removed from OpenMDAO in version 3.21. I added the necessary HTML functions to OpenMDAO-XDSM and checked the compatibility with OpenMDAO 3.23. 

@engineerjai thanks for flagging the problem. Now the master branch has the fix, and I also created a v0.7 tag. Please try to run your code and let me know if it works.
