### ISSUE TITLE
Diagram Differences with openmdao 3.3

### ISSUE THREAD

**Issue by JiaruiYangAtCornell** [onodip/OpenMDAO-XDSM#7]
Hi, just tried the example of **omxdsm/examples/sellar_xdsmjs.py** using openmdao 3.30. Generated the following diagram which is different from what it was supposed to be shown on the GitHub.

Any guideline for a clearer view?

<img width="1714" alt="image" src="https://github.com/onodip/OpenMDAO-XDSM/assets/112024195/262f4cc2-6129-46cf-9a5f-5189684cad21">

**Comment by onodip** [comment]
@JiaruiYangAtCornell you can control the looks of your diagram with the "include_indepvarcomps" and "class_names" arguments of the write_xdsm() function. If you set both of them to "False", you will get the following diagram:

<img width="1199" alt="image" src="https://github.com/onodip/OpenMDAO-XDSM/assets/34424189/8c04ca65-0d37-46ee-a7d4-03fa2bdfcb77">

You can read more about the available options here:
https://github.com/onodip/OpenMDAO-XDSM/tree/v1.0/omxdsm/docs/xdsm_visualization.rst
And in the docstring:
https://github.com/onodip/OpenMDAO-XDSM/tree/v1.0/omxdsm/xdsm_writer.py#L831

**Comment by onodip** [comment]
I updated the master branch and created a new tag, where this is the default setting in XDSMjs example.
https://github.com/onodip/OpenMDAO-XDSM/releases/tag/v1.1
